#!/bin/bash

# Dotfiles and bootstrap installer
# Installs git, clones repository and symlinks dotfiles to your home directory

if ! command -v git >/dev/null 2>&1; then
	echo "Error: Git is required."
	exit
fi

# Clone dotfiles and make symlinks
echo "Installing dotfiles..."
cd ~ && git clone https://github.com/reenl/dotfiles.git && cd dotfiles && ./sync
source ~/.bashrc
echo "Dotfiles installed successfully."
