#!/bin/bash

# Dotfiles and bootstrap installer
# Installs git, clones repository and symlinks dotfiles to your home directory

if ! command -v git >/dev/null 2>&1; then
	echo "Error: Git is required."
	exit
fi

# Clone dotfiles and make symlinks
echo "Installing dotfiles..."
cd ~ && git clone https://github.com/reenl/dotfiles.git &&
cd dotfiles &&
git submodule init &&
git submodule update &&
./sync

source ~/.bashrc

echo "Dotfiles installed successfully."

echo "Installing composer..."
curl -sS https://getcomposer.org/installer | php -- --install-dir=bin --filename=composer
echo "Composer installed successfully."
